services:
  - type: web
    name: titiraukawa
    env: python
    region: oregon  # or set closer to NZ: singapore
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python -m uvicorn backend.main:app --host 0.0.0.0 --port 8080
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_DB_URL
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: TRUSTED_HOSTS
        value: "*"
      - key: ENVIRONMENT
        value: "production"
