services:
  - type: web
    name: titiraukawa
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python -m uvicorn backend.main:app --host 0.0.0.0 --port 8080
    workingDirectory: /opt/render/project/src
